Repository julian-code/makersofdenmark, pull requests merged in 2020-10, with the labels that each got.

#27 feature/#16
  src/MakersOfDenmark.Application/MakersOfDenmark.Application.csproj
  src/MakersOfDenmark.Application/Queries/V1/GetAllMakerSpaces.cs
  src/MakersOfDenmark.Application/Queries/V1/GetMakerSpaceById.cs
  src/MakersOfDenmark.Application/Queries/V1/GetMakerSpaceToolsById.cs
  src/MakersOfDenmark.Domain/Models/Address.cs
  src/MakersOfDenmark.Domain/Models/Tool.cs
  src/MakersOfDenmark.Infrastructure/Migrations/20201020103732_Feature#16.Designer.cs
  src/MakersOfDenmark.Infrastructure/Migrations/20201020103732_Feature#16.cs
  src/MakersOfDenmark.WebAPI/Controllers/MakerSpaceController.cs
  tests/MakersOfDenmark.WebAPI.Tests/GetAllMakerSpacesRequestHandlerTests.cs
  tests/MakersOfDenmark.WebAPI.Tests/GetMakerSpaceByIdHandlerTests.cs
  tests/MakersOfDenmark.WebAPI.Tests/GetMakerSpaceToolsByIdHandlerTests.cs
  tests/MakersOfDenmark.WebAPI.Tests/RequestHandlerFixture.cs
Labels: enhancement

#26 Feature issue template
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/to_do.md
Labels: enhancement

#35 Feat/register maker space
  src/MakersOfDenmark.Application/Commands/V1/RegisterMakerSpace.cs
  src/MakersOfDenmark.Application/MakersOfDenmark.Application.csproj
  src/MakersOfDenmark.WebAPI/Controllers/MakerSpaceController.cs
  tests/MakersOfDenmark.WebAPI.Tests/RegisterMakerSpaceHandlerTest.cs
Labels: enhancement

#33 Created CD and CI pipelines
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  src/MakersOfDenmark.WebAPI/appsettings.Development.json
Labels: enhancement

#32 Added get events.
  src/MakersOfDenmark.Application/Queries/V1/GetMakerSpaceEventsById.cs
  src/MakersOfDenmark.WebAPI/Controllers/MakerSpaceController.cs
Labels: enhancement

#39 added
  .github/workflows/cd.yml
  .github/workflows/ci.yml
Labels: bug

#43 #42
  src/MakersOfDenmark.WebAPI/Startup.cs
Labels: enhancement

#45 #44
  src/MakersOfDenmark.Application/Commands/V1/RegisterMakerSpace.cs
  src/MakersOfDenmark.WebAPI/Startup.cs
  tests/MakersOfDenmark.WebAPI.Tests/RegisterMakerSpaceHandlerTest.cs
Labels: enhancement

#51 Get selection of makerspaces
  src/MakersOfDenmark.Application/Queries/V1/GetSelectionOfMakerSpaces.cs
  src/MakersOfDenmark.WebAPI/Controllers/MakerSpaceController.cs
  tests/MakersOfDenmark.WebAPI.Tests/GetSelectionOfMakerSpacesTest.cs
Labels: ready for review

#60 Added local logging and added elmah.io as distributed logging provider. Elmah.io is used as a 21-day trail.
  .gitignore
  src/MakersOfDenmark.WebAPI/MakersOfDenmark.WebAPI.csproj
  src/MakersOfDenmark.WebAPI/Program.cs
  src/MakersOfDenmark.WebAPI/Startup.cs
  src/MakersOfDenmark.WebAPI/appsettings.json
Labels: enhancement

#62 User Controller
  src/MakersOfDenmark.WebAPI/Controllers/UserController.cs
Labels: ready for review

#59 Fixed bug in endpoint and renamed for clarity
  MakersOfDenmark.Application.Test/Validators/MakerSpaceIdentifierValidatorTest.cs
  src/MakersOfDenmark.Application/Queries/V1/GetMakerSpaceById.cs
  src/MakersOfDenmark.Application/Queries/V1/GetSelectionOfMakerSpaces.cs
  src/MakersOfDenmark.Application/Queries/V1/SearchForMakerSpace.cs
  src/MakersOfDenmark.WebAPI/Controllers/MakerSpaceController.cs
  src/MakersOfDenmark.WebAPI/MakersOfDenmark.WebAPI-log.txt
  tests/MakersOfDenmark.WebAPI.Tests/AddMakerSpaceToolHandlerTest.cs
  tests/MakersOfDenmark.WebAPI.Tests/EditBaseMakerSpaceHandlerTest.cs
  tests/MakersOfDenmark.WebAPI.Tests/EditMakerSpaceAddressHandlerTest.cs
  tests/MakersOfDenmark.WebAPI.Tests/EditMakerSpaceContactInfoHandlerTest.cs
  tests/MakersOfDenmark.WebAPI.Tests/EditMakerSpaceOrganizationHandlerTest.cs
  tests/MakersOfDenmark.WebAPI.Tests/GetMakerSpaceByIdHandlerTests.cs
  tests/MakersOfDenmark.WebAPI.Tests/GetMakerSpaceToolsByIdHandlerTests.cs
  tests/MakersOfDenmark.WebAPI.Tests/GetSelectionOfMakerSpacesTest.cs
  tests/MakersOfDenmark.WebAPI.Tests/RemoveMakerSpaceToolHandlerTest.cs
  tests/MakersOfDenmark.WebAPI.Tests/RequestHandlerFixture.cs
  tests/MakersOfDenmark.WebAPI.Tests/SearchForMakerSpaceHandlerTest.cs
Labels: ready for review
